### PR TITLE
Better split

### PR DESCRIPTION
**Pull request by Joshix-1**
Breaking change! 
VelenCommand#getShortcuts() now returns a String[] so it doesn't get changed later.

The command parsing alg is reworked to be more readable.

The args get parsed more intelligent with respect to escapes and double qoutes.

### CODE REVIEW

**Comment by Joshix-1** [comment]
I also added a new util method to allow named arguments like:

**Comment by ShindouMihou** [comment]
I wonder if it would be better to make this a non-breaking change for now by adding the original methods but with a deprecated annotation instead unless I am missing a point here over "so it doesn't get changed later."? 🤔

**Comment by Joshix-1** [comment]
Lists can change their length, so returning an array is better, because it shouldn't change.

**Comment by ShindouMihou** [comment]
I see, is this ready to go or do you want to add more since I will be pushing it to the master branch to place it on its own version?

**Comment by Joshix-1** [comment]
Its ready to go

**Comment by ShindouMihou** [comment]
Thanks for the PR, then! 🧇

**Pull request merged**
